In [5]:
import numpy as np

In [ ]:
import pandas as pd
df = pd.read_csv('dataset_tk.csv')

In [ ]:
df.head()

In [ ]:
df['total'].max()

In [ ]:
df[df['total'] >= 4040.1]

In [ ]:
df['UP'].max()

In [ ]:
df[df['UP'] == 471.8]

In [122]:
import datetime

dt = datetime.datetime(2019, 3, 15,18)
end = datetime.datetime(2021, 3, 28,18)
step = datetime.timedelta(hours=24)

result = []

while dt < end:
    result.append(dt.strftime('%Y-%m-%d %H:%M'))
    dt += step

In [123]:
len(result)

744

In [124]:
datetime.datetime.strptime(result[2], '%Y-%m-%d %H:%M').weekday()

6

In [125]:
initial_reading = 10
weekend = [5,6]
summer_months = [4,5,6,7,8]
summer_pers = np.arange(10,20)
winter_pers = np.arange(8,18)
consumption_dict = {}
for date in result:
    stripped = datetime.datetime.strptime(date, '%Y-%m-%d %H:%M')
    day = stripped.weekday()
    month = stripped.month
    if month in summer_months:
        if day in weekend:
            # Make each of the last 5 elements 5x more likely
            prob = [1.0]*(len(summer_pers)-5) + [5.0]*5
            
            # Normalising to 1.0
            prob /= np.sum(prob)
            day_consumption  = np.random.choice(summer_pers, p = prob)
        else:
            
            day_consumption  = np.random.choice(summer_pers)
    else:
        if day in weekend:
            # Make each of the last 5 elements 5x more likely
            prob = [1.0]*(len(winter_pers)-5) + [5.0]*5
            
            # Normalising to 1.0
            prob /= np.sum(prob)
            day_consumption  = np.random.choice(winter_pers, p = prob)
       
        else:
            
            day_consumption  = np.random.choice(winter_pers)
            
        
    initial_reading += day_consumption
    
    
    consumption_dict[date] = initial_reading
            
print()

In [126]:
noise = np.random.laplace(loc=0, scale=1, size=len(consumption_dict))

In [127]:
import pandas as pd
df = pd.DataFrame(consumption_dict.items(), columns=['Date', 'DateValue'])

In [128]:
df['Date'] = pd.to_datetime(df['Date'])

In [129]:
df['month'] = df['Date'].dt.month

In [130]:
df['weekday'] = df['Date'].dt.day_name()

In [131]:
df['lag'] = df.DateValue.shift(1)

In [132]:
df['difference'] = df['DateValue'] - df['lag']

In [133]:
df['noise'] = noise

In [134]:
df['reading'] = df['DateValue'] + df['noise']

In [16]:
from statsmodels.tsa.seasonal import seasonal_decompose
from matplotlib import dates as mpld
import matplotlib

In [ ]:
plt.plot(df.iloc[:,1].index,df.reading.iloc[:,1])
plt.gcf().autofmt_xdate()
plt.title("Average Temperature of India (2000-2018)")
plt.xlabel("Time")
plt.ylabel("Temparature (Â°C)")
plt.show()

In [ ]:
plt.plot(df_selected['Date'], df_selected['reading'])
plt.gcf().autofmt_xdate()
date_format = mpld.DateFormatter('%Y-%m')
plt.gca().xaxis.set_major_formatter(date_format)
plt.title("Electric consumption")
plt.xlabel("Time")
plt.ylabel("Consumption")

In [135]:
df['Date'] = pd.to_datetime(df['Date'])
df.index = df['Date']

In [136]:
df = df[['reading']]

In [137]:
df.reset_index(inplace = True)

In [ ]:
result_add = seasonal_decompose(
    df['reading'], period=372, model='additive')
result_add.plot()
plt.gcf().autofmt_xdate()
date_format = mpld.DateFormatter('%Y-%m')
plt.gca().xaxis.set_major_formatter(date_format)
plt.rcParams["figure.figsize"]=(15, 10)

In [20]:
df.head(1)

                 Date    reading
0 2019-03-15 18:00:00  22.169644

In [138]:
df_train = df[df['Date'] < '2021-03-15']

In [139]:
df_train.index = df_train['Date']

In [140]:
del df_train['Date']

In [141]:
df.index = df['Date']

In [142]:
del df['Date']

In [143]:
from statsmodels.tsa.holtwinters import ExponentialSmoothing

model = ExponentialSmoothing(df_train, trend='additive',
                             seasonal='additive', seasonal_periods=12).fit(damping_slope= 1)

/home/utkarsh/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:163: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)

In [144]:
"""Brutlag Algorithm"""
PERIOD = 12        # The given time series has seasonal_period=12
GAMMA = 0.3684211  # the seasonility component
SF = 1.96          # brutlag scaling factor for the confidence bands.
UB = []            # upper bound or upper confidence band
LB = []            # lower bound or lower confidence band

In [147]:
model = ExponentialSmoothing(
    df_train, trend='additive', seasonal='additive').fit()
prediction = model.predict(
    start= df.iloc[:, 0].index[0], end=df.iloc[:, 0].index[-1])

/home/utkarsh/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:163: ValueWarning: No frequency information was provided, so inferred frequency D will be used.
  % freq, ValueWarning)
/home/utkarsh/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/holtwinters.py:725: ConvergenceWarning: Optimization failed to converge. Check mle_retvals.
  ConvergenceWarning)

In [148]:
difference_array = []
dt = []
difference_table = {
    "actual": df.iloc[:, 0], "predicted": prediction, "difference": difference_array, "UB": UB, "LB": LB}

In [149]:
"""Calculatation of confidence bands using brutlag algorithm"""
for i in range(len(prediction)):
    diff = df.iloc[:, 0][i]-prediction[i]
    if i < PERIOD:
        dt.append(GAMMA*abs(diff))
    else:
        dt.append(GAMMA*abs(diff) + (1-GAMMA)*dt[i-PERIOD])

    difference_array.append(diff)
    UB.append(prediction[i]+SF*dt[i])
    LB.append(prediction[i]-SF*dt[i])

print("\nDifference between actual and predicted\n")
difference = pd.DataFrame(difference_table)
print(difference)

Difference between actual and predicted

                           actual     predicted  difference            UB  \
2019-03-15 18:00:00     26.394632     29.676215   -3.281583     32.045864
2019-03-16 18:00:00     38.705741     38.309455    0.396286     38.595615
2019-03-17 18:00:00     54.294832     51.076196    3.218636     53.400390
2019-03-18 18:00:00     66.715442     62.899555    3.815887     65.655027
2019-03-19 18:00:00     80.631708     77.221513    3.410195     79.684033
2019-03-20 18:00:00     89.705872     87.415931    2.289941     89.069509
2019-03-21 18:00:00    103.408374    100.106252    3.302122    102.490732
2019-03-22 18:00:00    117.089023    108.142685    8.946338    114.602884
2019-03-23 18:00:00    131.952842    125.504867    6.447975    130.160984
2019-03-24 18:00:00    147.037877    143.476051    3.561826    146.048064
2019-03-25 18:00:00    160.651763    156.452836    4.198926    159.484903
2019-03-26 18:00:00    173.341932    171.482434    1.859498    172.825188
2019-03-27 18:00:00    183.524326    180.994588    2.529738    184.317946
2019-03-28 18:00:00    193.485237    194.960319   -1.475081    196.206216
2019-03-29 18:00:00    208.401826    203.722033    4.679794    208.569249
2019-03-30 18:00:00    222.147576    218.128615    4.018960    222.771026
2019-03-31 18:00:00    238.418418    233.874893    4.543524    238.711072
2019-04-01 18:00:00    251.428272    248.112108    3.316163    251.551093
2019-04-02 18:00:00    272.157102    261.991738   10.165363    270.838189
2019-04-03 18:00:00    286.301779    276.796016    9.505763    287.740304
2019-04-04 18:00:00    300.965068    293.290918    7.674149    301.773168
2019-04-05 18:00:00    314.235411    310.736734    3.498677    314.887577
2019-04-06 18:00:00    323.991754    325.136256   -1.144502    327.877696
2019-04-07 18:00:00    342.904288    339.228895    3.675393    342.730971
2019-04-08 18:00:00    361.155319    353.224463    7.930856    361.050339
2019-04-09 18:00:00    370.263103    373.674077   -3.410974    376.924042
2019-04-10 18:00:00    389.636120    381.622540    8.013580    390.470589
2019-04-11 18:00:00    403.032348    397.034145    5.998202    404.297528
2019-04-12 18:00:00    419.487933    412.153309    7.334624    420.504109
2019-04-13 18:00:00    431.246381    426.988917    4.257464    432.235245
...                           ...           ...         ...           ...
2021-02-26 18:00:00   9970.016819   9966.185794    3.831025   9973.273514
2021-02-27 18:00:00   9982.021974   9982.237796   -0.215822   9984.665340
2021-02-28 18:00:00   9998.720094   9993.479292    5.240802   9999.777334
2021-03-01 18:00:00  10010.572460  10012.367910   -1.795450  10018.989088
2021-03-02 18:00:00  10023.753129  10022.721102    1.032027  10026.374528
2021-03-03 18:00:00  10036.030994  10039.280228   -3.249234  10046.262812
2021-03-04 18:00:00  10043.594043  10050.611751   -7.017708  10058.436885
2021-03-05 18:00:00  10058.600687  10057.700489    0.900198  10065.213019
2021-03-06 18:00:00  10070.551779  10070.182178    0.369601  10075.115253
2021-03-07 18:00:00  10085.241959  10084.218373    1.023585  10088.668688
2021-03-08 18:00:00  10094.497678  10097.364743   -2.867065  10105.027895
2021-03-09 18:00:00  10113.147050  10108.280291    4.866759  10114.701643
2021-03-10 18:00:00  10119.466601  10124.700024   -5.233424  10132.955562
2021-03-11 18:00:00  10128.477193  10133.029383   -4.552190  10137.849730
2021-03-12 18:00:00  10141.792235  10145.047094   -3.254859  10151.375155
2021-03-13 18:00:00  10150.555065  10154.881104   -4.326039  10162.186756
2021-03-14 18:00:00  10162.951450  10166.444268   -3.492817  10171.273876
2021-03-15 18:00:00  10176.149865  10174.961158    1.188708  10180.229583
2021-03-16 18:00:00  10193.033907  10190.701843    2.332064  10197.328028
2021-03-17 18:00:00  10204.725461  10199.322923    5.402538  10207.968880
2021-03-18 18:00:00  10219.557271  10210.390131    9.167140  10220.125398
2021-03-19 18:00:00  10230.743125  10225.177821    5.565304  10232.007282
2021-03-20 18:00:00  10244.633818  10236.047748    8.586070  10247.087681
2021-03-21 18:00:00  10256.563083  10251.861113    4.701969  10259.312022
2021-03-22 18:00:00  10271.770536  10262.216328    9.554208  10274.329496
2021-03-23 18:00:00  10285.348427  10277.957013    7.391413  10286.338822
2021-03-24 18:00:00  10297.597885  10286.578094   11.019792  10298.532214
2021-03-25 18:00:00  10311.333971  10297.645302   13.688669  10312.144059
2021-03-26 18:00:00  10321.171691  10312.432992    8.738699  10321.793532
2021-03-27 18:00:00  10338.223927  10323.302919   14.921008  10337.404885

                               LB
2019-03-15 18:00:00     27.306566
2019-03-16 18:00:00     38.023295
2019-03-17 18:00:00     48.752001
2019-03-18 18:00:00     60.144083
2019-03-19 18:00:00     74.758994
2019-03-20 18:00:00     85.762352
2019-03-21 18:00:00     97.721772
2019-03-22 18:00:00    101.682486
2019-03-23 18:00:00    120.848749
2019-03-24 18:00:00    140.904037
2019-03-25 18:00:00    153.420769
2019-03-26 18:00:00    170.139680
2019-03-27 18:00:00    177.671231
2019-03-28 18:00:00    193.714422
2019-03-29 18:00:00    198.874816
2019-03-30 18:00:00    213.486205
2019-03-31 18:00:00    229.038714
2019-04-01 18:00:00    244.673123
2019-04-02 18:00:00    253.145287
2019-04-03 18:00:00    265.851729
2019-04-04 18:00:00    284.808668
2019-04-05 18:00:00    306.585891
2019-04-06 18:00:00    322.394815
2019-04-07 18:00:00    335.726819
2019-04-08 18:00:00    345.398586
2019-04-09 18:00:00    370.424112
2019-04-10 18:00:00    372.774491
2019-04-11 18:00:00    389.770763
2019-04-12 18:00:00    403.802509
2019-04-13 18:00:00    421.742590
...                           ...
2021-02-26 18:00:00   9959.098075
2021-02-27 18:00:00   9979.810251
2021-02-28 18:00:00   9987.181250
2021-03-01 18:00:00  10005.746732
2021-03-02 18:00:00  10019.067675
2021-03-03 18:00:00  10032.297643
2021-03-04 18:00:00  10042.786617
2021-03-05 18:00:00  10050.187960
2021-03-06 18:00:00  10065.249103
2021-03-07 18:00:00  10079.768059
2021-03-08 18:00:00  10089.701590
2021-03-09 18:00:00  10101.858938
2021-03-10 18:00:00  10116.444487
2021-03-11 18:00:00  10128.209037
2021-03-12 18:00:00  10138.719033
2021-03-13 18:00:00  10147.575452
2021-03-14 18:00:00  10161.614659
2021-03-15 18:00:00  10169.692732
2021-03-16 18:00:00  10184.075657
2021-03-17 18:00:00  10190.676966
2021-03-18 18:00:00  10200.654864
2021-03-19 18:00:00  10218.348361
2021-03-20 18:00:00  10225.007816
2021-03-21 18:00:00  10244.410205
2021-03-22 18:00:00  10250.103161
2021-03-23 18:00:00  10269.575205
2021-03-24 18:00:00  10274.623973
2021-03-25 18:00:00  10283.146545
2021-03-26 18:00:00  10303.072452
2021-03-27 18:00:00  10309.200953

[744 rows x 5 columns]

In [150]:
normal = []
normal_date = []
anomaly = []
anomaly_date = []

In [151]:
df_2 = pd.DataFrame(prediction[prediction.index >'2021-03-14 18:00:00'])

In [152]:
df_1 = df[df.index <= '2021-03-15']

In [153]:
df_1

                          reading
Date
2019-03-15 18:00:00     26.394632
2019-03-16 18:00:00     38.705741
2019-03-17 18:00:00     54.294832
2019-03-18 18:00:00     66.715442
2019-03-19 18:00:00     80.631708
2019-03-20 18:00:00     89.705872
2019-03-21 18:00:00    103.408374
2019-03-22 18:00:00    117.089023
2019-03-23 18:00:00    131.952842
2019-03-24 18:00:00    147.037877
2019-03-25 18:00:00    160.651763
2019-03-26 18:00:00    173.341932
2019-03-27 18:00:00    183.524326
2019-03-28 18:00:00    193.485237
2019-03-29 18:00:00    208.401826
2019-03-30 18:00:00    222.147576
2019-03-31 18:00:00    238.418418
2019-04-01 18:00:00    251.428272
2019-04-02 18:00:00    272.157102
2019-04-03 18:00:00    286.301779
2019-04-04 18:00:00    300.965068
2019-04-05 18:00:00    314.235411
2019-04-06 18:00:00    323.991754
2019-04-07 18:00:00    342.904288
2019-04-08 18:00:00    361.155319
2019-04-09 18:00:00    370.263103
2019-04-10 18:00:00    389.636120
2019-04-11 18:00:00    403.032348
2019-04-12 18:00:00    419.487933
2019-04-13 18:00:00    431.246381
...                           ...
2021-02-13 18:00:00   9807.007364
2021-02-14 18:00:00   9822.564488
2021-02-15 18:00:00   9835.460027
2021-02-16 18:00:00   9847.993716
2021-02-17 18:00:00   9866.535961
2021-02-18 18:00:00   9877.498116
2021-02-19 18:00:00   9884.423346
2021-02-20 18:00:00   9898.131052
2021-02-21 18:00:00   9904.994501
2021-02-22 18:00:00   9919.539474
2021-02-23 18:00:00   9929.107370
2021-02-24 18:00:00   9943.679387
2021-02-25 18:00:00   9957.171012
2021-02-26 18:00:00   9970.016819
2021-02-27 18:00:00   9982.021974
2021-02-28 18:00:00   9998.720094
2021-03-01 18:00:00  10010.572460
2021-03-02 18:00:00  10023.753129
2021-03-03 18:00:00  10036.030994
2021-03-04 18:00:00  10043.594043
2021-03-05 18:00:00  10058.600687
2021-03-06 18:00:00  10070.551779
2021-03-07 18:00:00  10085.241959
2021-03-08 18:00:00  10094.497678
2021-03-09 18:00:00  10113.147050
2021-03-10 18:00:00  10119.466601
2021-03-11 18:00:00  10128.477193
2021-03-12 18:00:00  10141.792235
2021-03-13 18:00:00  10150.555065
2021-03-14 18:00:00  10162.951450

[731 rows x 1 columns]

In [154]:
df_2.rename({0:'reading'},axis =1,inplace=True)

In [155]:
df_3 = pd.concat([df_1,df_2])

In [156]:
df_3

                          reading
2019-03-15 18:00:00     26.394632
2019-03-16 18:00:00     38.705741
2019-03-17 18:00:00     54.294832
2019-03-18 18:00:00     66.715442
2019-03-19 18:00:00     80.631708
2019-03-20 18:00:00     89.705872
2019-03-21 18:00:00    103.408374
2019-03-22 18:00:00    117.089023
2019-03-23 18:00:00    131.952842
2019-03-24 18:00:00    147.037877
2019-03-25 18:00:00    160.651763
2019-03-26 18:00:00    173.341932
2019-03-27 18:00:00    183.524326
2019-03-28 18:00:00    193.485237
2019-03-29 18:00:00    208.401826
2019-03-30 18:00:00    222.147576
2019-03-31 18:00:00    238.418418
2019-04-01 18:00:00    251.428272
2019-04-02 18:00:00    272.157102
2019-04-03 18:00:00    286.301779
2019-04-04 18:00:00    300.965068
2019-04-05 18:00:00    314.235411
2019-04-06 18:00:00    323.991754
2019-04-07 18:00:00    342.904288
2019-04-08 18:00:00    361.155319
2019-04-09 18:00:00    370.263103
2019-04-10 18:00:00    389.636120
2019-04-11 18:00:00    403.032348
2019-04-12 18:00:00    419.487933
2019-04-13 18:00:00    431.246381
...                           ...
2021-02-26 18:00:00   9970.016819
2021-02-27 18:00:00   9982.021974
2021-02-28 18:00:00   9998.720094
2021-03-01 18:00:00  10010.572460
2021-03-02 18:00:00  10023.753129
2021-03-03 18:00:00  10036.030994
2021-03-04 18:00:00  10043.594043
2021-03-05 18:00:00  10058.600687
2021-03-06 18:00:00  10070.551779
2021-03-07 18:00:00  10085.241959
2021-03-08 18:00:00  10094.497678
2021-03-09 18:00:00  10113.147050
2021-03-10 18:00:00  10119.466601
2021-03-11 18:00:00  10128.477193
2021-03-12 18:00:00  10141.792235
2021-03-13 18:00:00  10150.555065
2021-03-14 18:00:00  10162.951450
2021-03-15 18:00:00  10174.961158
2021-03-16 18:00:00  10190.701843
2021-03-17 18:00:00  10199.322923
2021-03-18 18:00:00  10210.390131
2021-03-19 18:00:00  10225.177821
2021-03-20 18:00:00  10236.047748
2021-03-21 18:00:00  10251.861113
2021-03-22 18:00:00  10262.216328
2021-03-23 18:00:00  10277.957013
2021-03-24 18:00:00  10286.578094
2021-03-25 18:00:00  10297.645302
2021-03-26 18:00:00  10312.432992
2021-03-27 18:00:00  10323.302919

[744 rows x 1 columns]

22.691525516533478

In [157]:
for i in range(len(df_3.iloc[:, 0].index)):
    print(i)
    if (UB[i] <= df_3.iloc[:, 0][i] or LB[i] >= df_3.iloc[:, 0][i]) and i > PERIOD:
        anomaly_date.append(df_3.iloc[:, 0].index[i])
        anomaly.append(df_3.iloc[:, 0][i])
        
    else:
        normal_date.append(df_3.iloc[:, 0].index[i])
        normal.append(df_3.iloc[:, 0][i])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743

In [158]:

anomaly = pd.DataFrame({"date": anomaly_date, "value": anomaly})
anomaly.set_index('date', inplace=True)
normal = pd.DataFrame({"date": normal_date, "value": normal})
normal.set_index('date', inplace=True)

In [160]:
anom

                            value
date
2019-03-15 18:00:00     26.394632
2019-03-16 18:00:00     38.705741
2019-03-17 18:00:00     54.294832
2019-03-18 18:00:00     66.715442
2019-03-19 18:00:00     80.631708
2019-03-20 18:00:00     89.705872
2019-03-21 18:00:00    103.408374
2019-03-22 18:00:00    117.089023
2019-03-23 18:00:00    131.952842
2019-03-24 18:00:00    147.037877
2019-03-25 18:00:00    160.651763
2019-03-26 18:00:00    173.341932
2019-03-27 18:00:00    183.524326
2019-03-29 18:00:00    208.401826
2019-03-30 18:00:00    222.147576
2019-03-31 18:00:00    238.418418
2019-04-01 18:00:00    251.428272
2019-04-03 18:00:00    286.301779
2019-04-04 18:00:00    300.965068
2019-04-05 18:00:00    314.235411
2019-04-06 18:00:00    323.991754
2019-04-10 18:00:00    389.636120
2019-04-11 18:00:00    403.032348
2019-04-12 18:00:00    419.487933
2019-04-13 18:00:00    431.246381
2019-04-14 18:00:00    448.444397
2019-04-15 18:00:00    460.333094
2019-04-16 18:00:00    470.165031
2019-04-17 18:00:00    489.602641
2019-04-18 18:00:00    502.517670
...                           ...
2021-02-26 18:00:00   9970.016819
2021-02-27 18:00:00   9982.021974
2021-02-28 18:00:00   9998.720094
2021-03-01 18:00:00  10010.572460
2021-03-02 18:00:00  10023.753129
2021-03-03 18:00:00  10036.030994
2021-03-04 18:00:00  10043.594043
2021-03-05 18:00:00  10058.600687
2021-03-06 18:00:00  10070.551779
2021-03-07 18:00:00  10085.241959
2021-03-08 18:00:00  10094.497678
2021-03-09 18:00:00  10113.147050
2021-03-10 18:00:00  10119.466601
2021-03-11 18:00:00  10128.477193
2021-03-12 18:00:00  10141.792235
2021-03-13 18:00:00  10150.555065
2021-03-14 18:00:00  10162.951450
2021-03-15 18:00:00  10174.961158
2021-03-16 18:00:00  10190.701843
2021-03-17 18:00:00  10199.322923
2021-03-18 18:00:00  10210.390131
2021-03-19 18:00:00  10225.177821
2021-03-20 18:00:00  10236.047748
2021-03-21 18:00:00  10251.861113
2021-03-22 18:00:00  10262.216328
2021-03-23 18:00:00  10277.957013
2021-03-24 18:00:00  10286.578094
2021-03-25 18:00:00  10297.645302
2021-03-26 18:00:00  10312.432992
2021-03-27 18:00:00  10323.302919

[730 rows x 1 columns]